apiVersion: v1
kind: ConfigMap
metadata:
  name: volodina-hw5
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: Secret
metadata:
  name: volodina-hw5-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_HOST: {{ include "postgresql.fullname" . | b64enc | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote  }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote  }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
